version: '2.2'
services:
  git:
    image: "jeffvogt/workshop-git:2.2.0"
    ports:
     - "2222:22"

  jenkins:
    image: "jeffvogt/workshop-jenkins:3.1.1"
    ports:
     - "8080:8080"
    volumes:
      - /var/run:/var/run:rw

  sonar:
    image: "jeffvogt/workshop-sonar:1.0.1"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    restart: always
    ports:
     - "9000:9000"