version: '3'
services:
  git:
    image: "jeffvogt/workshop-git:2.1.0"
    ports:
     - "2222:22"

  jenkins:
    image: "jeffvogt/workshop-jenkins:3.1.0"
    ports:
     - "8080:8080"

    volumes:
      - /var/run:/var/run:rw